name: onekwacha
description: A Mobile Payments App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.3.1
  intl_phone_number_input: ^0.5.2+2
  page_transition: ^1.1.7+5
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.2.1
  currency_text_input_formatter: ^1.0.3
  firebase_core: ^0.5.0
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.14.4
  intl: ^0.16.1
  firebase_auth: ^0.18.4+1
  # intl: ^0.15.7
  # moneytextformfield: ^0.3.5+1  
  # barcode_scan:
  # path_provider:
  # flutter_vector_icons:
# dependency_overrides:
#   intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/calender.png
   - assets/images/card_cvv.png
   - assets/images/visa.png
   - assets/images/jcb.png
   - assets/images/verve.png
   - assets/images/discover.png
   - assets/images/american_express.png
   - assets/images/dinners_club.png
   - assets/images/mastercard.png
   - assets/slider/Ad1.jpg
   - assets/slider/Ad2.jpg
   - assets/slider/Ad3.jpg
   - assets/slider/Ad4.jpg
   - assets/slider/Ad5.jpg
   - assets/banks/Absa.png
   - assets/banks/Access.png
   - assets/banks/Ecobank.png
   - assets/banks/FNB.png
   - assets/banks/Stanchart.png
   - assets/banks/Zanaco.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: BaiJamJuree
      fonts:
        - asset: fonts/BaiJamjuree-Regular.ttf

    - family: Metrophobic
      fonts:
        - asset: fonts/Metrophobic-Regular.ttf

    - family: Suravaram
      fonts:
        - asset: fonts/Suravaram-Regular.ttf

    - family:  CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
