/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData money_transfer = IconData(0xf100, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_money = IconData(0xf101, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData initiate_money_transfer = IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_approved = IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_app = IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction = IconData(0xf106, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_and_change = IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xf108, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_2 = IconData(0xf109, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xf10a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receive_cash = IconData(0xf10b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_for_payment = IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency_exchange = IconData(0xf10d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xf10e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_in_hand = IconData(0xf110, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_payment = IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_counter = IconData(0xf112, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa = IconData(0xf113, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData get_cash = IconData(0xf114, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_on_delivery = IconData(0xf115, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insert_card = IconData(0xf116, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out = IconData(0xf117, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_receipt = IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_receipt = IconData(0xf119, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill = IconData(0xf11a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_list = IconData(0xf11c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_declined = IconData(0xf11d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_account = IconData(0xf11e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_approved = IconData(0xf11f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_machine = IconData(0xf120, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xf121, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wall_clock = IconData(0xf122, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_clock = IconData(0xf123, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_on = IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_off = IconData(0xf125, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xf126, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xf127, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_30 = IconData(0xf128, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sand_clock = IconData(0xf129, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xf12a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xf12b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_earth = IconData(0xf12c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_do = IconData(0xf12d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData increase = IconData(0xf12e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf12f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_shopping_cart = IconData(0xf131, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xf132, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_shopping_cart = IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xf134, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipped = IconData(0xf135, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivered = IconData(0xf136, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tracking = IconData(0xf137, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xf138, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData received = IconData(0xf139, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handle_with_care = IconData(0xf13a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_tick = IconData(0xf13b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xf13c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData around_the_globe = IconData(0xf13d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product = IconData(0xf13f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData door_to_door_delivery = IconData(0xf140, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kick_scooter = IconData(0xf141, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_truck = IconData(0xf142, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website = IconData(0xf143, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wi_fi = IconData(0xf144, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wi_fi_off = IconData(0xf145, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wi_fi_connected = IconData(0xf146, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xf147, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cellular_network = IconData(0xf148, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xf149, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_on = IconData(0xf14a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xf14b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype = IconData(0xf14c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf14d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf14e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out = IconData(0xf14f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter = IconData(0xf150, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signin = IconData(0xf151, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xf152, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_sign = IconData(0xf153, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xf154, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in = IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xf156, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xf157, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_verified = IconData(0xf158, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checked = IconData(0xf159, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_and_credit_card = IconData(0xf15a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData communicate = IconData(0xf15b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_search = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xf15d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_box = IconData(0xf15e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xf15f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_money = IconData(0xf160, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xf161, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_id = IconData(0xf162, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData protect = IconData(0xf163, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xf164, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData touch_id = IconData(0xf165, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iphone = IconData(0xf166, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xf168, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf169, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_call = IconData(0xf16a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xf16b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checked_checkbox = IconData(0xf16c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_declined = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xf16e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xf16f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xf170, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_page = IconData(0xf171, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xf172, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insert_credit_card = IconData(0xf173, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_wallet = IconData(0xf174, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sim_card = IconData(0xf175, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_sim_card = IconData(0xf176, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mastercard = IconData(0xf177, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData american_express = IconData(0xf178, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invite = IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData name = IconData(0xf17a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_cards = IconData(0xf17b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female_profile = IconData(0xf17c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male_user = IconData(0xf17d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfc_c = IconData(0xf17e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timesheet = IconData(0xf17f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stripe = IconData(0xf180, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pos_terminal = IconData(0xf181, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_building = IconData(0xf182, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_box = IconData(0xf183, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData department = IconData(0xf184, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData museum = IconData(0xf185, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack_of_money = IconData(0xf186, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xf187, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_euro = IconData(0xf188, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
